title:              jaemin's Development blog
email:              yjm8440@naver.com
description:        slow but steady
author:             Yoon jae min
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://jaeminyooon.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    JaeMinYooon
facebook_username:  윤재민
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
